/* 
**  mod_php_stub.c -- Apache sample php_stub module
**  [Autogenerated via ``apxs -n php_stub -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_php_stub.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /php_stub in as follows:
**
**    #   httpd.conf
**    LoadModule php_stub_module modules/mod_php_stub.so
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
*/

/*
**  mod_php_stub.cの動作テスト要件
**
** .htaccessに
**   - php_value
**   - php_flag
** を設定して500エラーを出力するかどうか
**
**  PHPStubErrorDocumentを設定している場合
**    - 500エラー時に PHPStubErrorDocument に設定したHTMLが出力されるか
**
**  PHPStubErrorDocumentを設定していない場合
**    - 500エラー時に シンプルなメッセージが返っているかどうか
**
**/

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "http_log.h"
#include "ap_config.h"

module AP_MODULE_DECLARE_DATA php_stub_module;

/* fork()語は読み取り専用 */
static const char *php_stub_error_document = NULL;
static const char *php_stub_error_link     = NULL;

typedef struct {
    bool should_alert;          /* .htaccessにサポートしてないcommandがあったらtrueになる */
} php_stub_conf_rec;

void *create_php_stub_config(apr_pool_t *p, char *dummy)
{
    php_stub_conf_rec *conf = (php_stub_conf_rec *) apr_pcalloc(p, sizeof(php_stub_conf_rec));
    conf->should_alert = false;
    return (void *) conf;
}

void *merge_php_stub_config(apr_pool_t *p, void *base_conf, void *new_conf)
{
    return new_conf;
}

static void php_stub_log_error(cmd_parms *cmd)
{
    ap_directive_t *d = cmd->directive;
    ap_log_error(APLOG_MARK, APLOG_ALERT, 0, cmd->server, 
                 "%s '%s': Invalid command '%s', perhaps mis-spelled or defined by a module"
                 "not included in the server configuration",
                 cmd->server->server_hostname,
                 d->filename,
                 d->directive);
}


/* サーバーが起動する時だけ実行 */
static const char *php_stub_set_error_document(cmd_parms *cmd, void *dummy, const char *path)
{
    const char *abs_path = ap_server_root_relative(cmd->pool, path);
    php_stub_error_document = (const char *)apr_pstrdup(cmd->pool, abs_path);
    return NULL;
}

/* サーバーが起動する時だけ実行 */
static const char *php_stub_set_error_link(cmd_parms *cmd, void *dummy, const char *link)
{
    php_stub_error_link = (const char *)apr_pstrdup(cmd->pool, link);
    return NULL;
}

/* htaccessのパース時にコールバック */
static const char *php_stub_apache_phpini_set(cmd_parms *cmd, void *dummy, const char *arg)
{
    php_stub_conf_rec *conf = dummy;
    conf->should_alert = true;
    php_stub_log_error(cmd);
    return NULL;
}

/* htaccessのパース時にコールバック */
static const char *php_stub_apache_value_handler(cmd_parms *cmd, void *dummy, const char *name, const char *value)
{
    php_stub_conf_rec *conf = dummy;
    conf->should_alert = true;
    php_stub_log_error(cmd);
    return NULL;
}

static apr_status_t php_stub_send_error_document(request_rec *r)
{
    apr_status_t status;
    apr_finfo_t finfo;
    apr_file_t *fd = NULL;
    conn_rec *c = r->connection;
    apr_bucket_brigade *bb;
    apr_bucket *e;

    /* ファイルがあるかどうか */
    status = apr_stat(&finfo, php_stub_error_document, APR_FINFO_TYPE, r->pool);
    if(APR_SUCCESS != status) {
        ap_log_rerror(APLOG_MARK, APLOG_ERR, status, r,
                     "PHPStubErrorDocument '%s'", php_stub_error_document );
        return APR_ENOSTAT;
    }

    /* 通常ファイル以外 .. ディレクトリなんぞを指定した場合 */
    if (APR_REG != finfo.filetype) {
        ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r,
                      "mod_php_stub.c Attempt to serve non regular file: %s", php_stub_error_document);
        return APR_EGENERAL;
    }

    /* ファイルオープン */
    status = apr_file_open(&fd, php_stub_error_document, APR_READ, 0, r->pool);
    if (APR_SUCCESS != status) {
        ap_log_rerror(APLOG_MARK, APLOG_ERR, status, r,
                      "mod_php_stub.c file permissions deny server access: %s", r->filename);
        return APR_EGENERAL;
    }

    /*
    **  brigadeでHTMLを返す. default_handlerからコードコピペ。
    **  (静的ファイルを簡単に返すための内部APIがありそう ...)
    **
    **  ap_internal_redirect()はレスポンスコードを指定できなそうなのと余計なフ
    **  入るでの使わなかった
    **
    */
    bb = apr_brigade_create(r->pool, c->bucket_alloc);

    if (sizeof(apr_off_t) > sizeof(apr_size_t)
        && r->finfo.size > AP_MAX_SENDFILE) {
        apr_off_t fsize = r->finfo.size;
        e = apr_bucket_file_create(fd, 0, AP_MAX_SENDFILE, r->pool,
                                   c->bucket_alloc);
        while (fsize > AP_MAX_SENDFILE) {
            apr_bucket *ce;
            apr_bucket_copy(e, &ce);
            APR_BRIGADE_INSERT_TAIL(bb, ce);
            e->start += AP_MAX_SENDFILE;
            fsize -= AP_MAX_SENDFILE;
        }
        e->length = (apr_size_t)fsize; /* Resize just the last bucket */
    }
    else {
        e = apr_bucket_file_create(fd, 0, (apr_size_t)r->finfo.size,
                                   r->pool, c->bucket_alloc);
    }

    APR_BRIGADE_INSERT_TAIL(bb, e);
    e = apr_bucket_eos_create(c->bucket_alloc);
    APR_BRIGADE_INSERT_TAIL(bb, e);

    status = ap_pass_brigade(r->output_filters, bb);
    if (status == APR_SUCCESS || c->aborted) {
        ap_log_rerror(APLOG_MARK, APLOG_DEBUG, status, r,
                      "mod_php_stub.c: sent %s as PHPStubErrorDocument", php_stub_error_document);
        return APR_SUCCESS; /* r->status will be respected */
    }
    else {
        /* no way to know what type of error occurred */
        ap_log_rerror(APLOG_MARK, APLOG_DEBUG, status, r,
                      "mod_php_stub.c: ap_pass_brigade returned %i", status);
        return APR_EGENERAL;
    }
}

static int php_stub_handler(request_rec *r)
{
    php_stub_conf_rec *conf = ap_get_module_config(r->per_dir_config, &php_stub_module);

    /* confがNULLの状態はありえなそうだけどテストしておく */
    if (NULL == conf) {
        ap_log_rerror(APLOG_MARK, APLOG_NOTICE, 0, r,
                      "mod_php_stub.c: ap_get_module_config() return NULL...something wrong ?");
        return DECLINED;
    }

    /* 何もしなくてok */
    if (false == conf->should_alert) {
        return DECLINED;
    }

    r->status = HTTP_INTERNAL_SERVER_ERROR;
    r->content_type = "text/html";

    /* PHPStubErrorDocumentがあればその内容を返す */
    if (php_stub_error_document && APR_SUCCESS == php_stub_send_error_document(r)) {
        return OK;
    }

    /* PHPStubErrorDocumentがなければ下記の警告HTMLを返す */
    ap_rputs("<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">"
             "<html><head>\n"
             "<title>500 Internal Server Error</title>\n"
             "</head><body>\n"
             "<h1>Internal Server Error</h1>\n"
             "<h3>.htaccess is invalid </h3>\n"
             "<p>The server not support following .htaccess commands</p>\n"
             "<ul>\n"
             "<li>php_value</li>\n"
             "<li>php_flag</li>\n"
             "<li>php_admin_value</li>\n"
             "<li>php_admin_flag</li>\n"
             "<li>PHPINIDir</li>\n"
             "</ul>\n"
             "<p>Please check your .htaccess and remove these commands.</p>\n"
             "<hr/>\n"
             ,r);

    if (NULL != php_stub_error_link) {
        ap_rprintf(r, "see also <a href='%s'>%s</a>\n",
                   php_stub_error_link,
                   php_stub_error_link );
    }
    ap_rputs("</body>\n</html>", r);

    return OK;
}

static void php_stub_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(php_stub_handler, NULL, NULL, APR_HOOK_REALLY_FIRST);
}

/* SEE ALSO http://blog.endflow.net/?lang=ja&p=48 */
const command_rec php_stub_dir_cmds[] =
{
    AP_INIT_TAKE1("PHPStubErrorDocument", php_stub_set_error_document, NULL, RSRC_CONF, "error document for php stub"),
    AP_INIT_TAKE1("PHPStubErrorLink",     php_stub_set_error_link,     NULL, RSRC_CONF, "error page for php stub"),
    /* Code taken from php-5.2.11/sapi/apache2filter/{sapi_apache2,apache_config}.c */
    AP_INIT_TAKE2("php_value",       php_stub_apache_value_handler, NULL, OR_OPTIONS, "PHP Value Modifier"),
    AP_INIT_TAKE2("php_flag",        php_stub_apache_value_handler, NULL, OR_OPTIONS, "PHP Flag Modifier"),
    AP_INIT_TAKE2("php_admin_value", php_stub_apache_value_handler, NULL, ACCESS_CONF|RSRC_CONF, "PHP Value Modifier (Admin)"),
    AP_INIT_TAKE2("php_admin_flag",  php_stub_apache_value_handler, NULL, ACCESS_CONF|RSRC_CONF, "PHP Flag Modifier (Admin)"),
    AP_INIT_TAKE1("PHPINIDir",       php_stub_apache_phpini_set,    NULL, RSRC_CONF, "Directory containing the php.ini file"),
    {NULL}
};

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA php_stub_module = {
    STANDARD20_MODULE_STUFF,
    create_php_stub_config,  /* create per-dir    config structures */
    merge_php_stub_config,   /* merge  per-dir    config structures */
    NULL,                    /* create per-server config structures */
    NULL,                    /* merge  per-server config structures */
    php_stub_dir_cmds,       /* table of config file commands       */
    php_stub_register_hooks  /* register hooks                      */
};
